/*
Copyright 2019 eterna2

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	helmoperatore2fyiv1alpha1 "github.com/e2fyi/k8s-helm-operator/pkg/apis/helmoperator.e2.fyi/v1alpha1"
	versioned "github.com/e2fyi/k8s-helm-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/e2fyi/k8s-helm-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/e2fyi/k8s-helm-operator/pkg/client/listers/helmoperator.e2.fyi/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// HelmOperationInformer provides access to a shared informer and lister for
// HelmOperations.
type HelmOperationInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.HelmOperationLister
}

type helmOperationInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewHelmOperationInformer constructs a new informer for HelmOperation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewHelmOperationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredHelmOperationInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredHelmOperationInformer constructs a new informer for HelmOperation type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredHelmOperationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HelmoperatorV1alpha1().HelmOperations(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.HelmoperatorV1alpha1().HelmOperations(namespace).Watch(options)
			},
		},
		&helmoperatore2fyiv1alpha1.HelmOperation{},
		resyncPeriod,
		indexers,
	)
}

func (f *helmOperationInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredHelmOperationInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *helmOperationInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&helmoperatore2fyiv1alpha1.HelmOperation{}, f.defaultInformer)
}

func (f *helmOperationInformer) Lister() v1alpha1.HelmOperationLister {
	return v1alpha1.NewHelmOperationLister(f.Informer().GetIndexer())
}
